### PR TITLE
Add documentation for custom functions

### PR DESCRIPTION
**Pull request by hubgit**
Document how to use `registerCustomXPathFunction` from `fontoxpath` to register custom XPath functions.

### CODE REVIEW

**Comment by hubgit** [comment]
@wvbe BTW, I'm very pleased to find this module, as I'd been working sporadically [in a similar direction](https://github.com/JATS4R/jats-validator/blob/5d7e19578a8afc4155720e45e3bab5717fdb8933/functions/lib/Schematron.js).

**Comment by wvbe** [comment]
Hey @hubgit , thank you so much for the PR and glad to hear you find this interesting.

I guess you're right to document this, custom XPath functions are very interesting in context of schematron. I feel that for that reason it would be better to expose `registerCustomXPathFunction` via `node-schematron` -- this would allow `node-schematron` to switch out the XPath implementation for another in the future, and to not break something if the `registerCustomXPathFunction` in `fontoxpath` changes. IMHO it's sort of a fluke that custom XPath functions are registered to `fontoxpath` "globally" (ie. I cannot `new FontoXpath()` and then register).

What's your opinion on this?

**Comment by hubgit** [comment]
I think if you're happy to add it then exposing `registerCustomXPathFunction` through `node-schematron` makes a lot of sense, for the reasons you describe.

**Comment by wvbe** [comment]
I'm probably a bit clumsy with GitHub but in order to amend your PR with another commit I pulled your branch into a new branch, made commit and pushed it to wvbe/node-schematron.

This would be my suggestion:
https://github.com/wvbe/node-schematron/commit/2decc09f90c57099f62c1310dcda2bc4b3246cbb

**Comment by hubgit** [comment]
> in order to amend your PR with another commit I pulled your branch into a new branch, made commit and pushed it to wvbe/node-schematron.

Looks good! I meant to close this pull request for a new one from your branch, but didn't get to it in time - thanks for merging 😅

**Comment by wvbe** [comment]
Thanks for PR'ing @hubgit!

**Pull request merged**
